const authentication = {
  LOGIN: 'LOGIN',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  LOGOUT: 'LOGOUT',
};
const info = {
  SAVE_PROFILE: 'SAVE_PROFILE',
};
const debtReminder = {
  GET_ALL_DEBT_REMINDERS: 'GET_ALL_DEBT_REMINDERS',
  GET_LIST_RECEIVER: 'GET_LIST_RECEIVER',
  CONNECT_SOCKET_IO_HOST: 'CONNECT_SOCKET_IO_HOST',
};
const transfer = {
  GET_LIST_RECEIVERS: 'GET_LIST_RECEIVERS',
  UPDATE_LIST_RECEIVERS: 'UPDATE_LIST_RECEIVERS',
};
const historyDeal ={
  GET_HISTORY_TRANSFER_CUSTOMER:'GET_HISTORY_TRANSFER_CUSTOMER', 
  GET_HISTORY_RECEIVE_CUSTOMER:'GET_HISTORY_RECEIVE_CUSTOMER', 
  GET_HISTORY_PAY_DEBT_CUSTOMER:'GET_HISTORY_PAY_DEBT_CUSTOMER', 
};
export const customerConstants = {
  authentication,
  info,
  debtReminder,
  transfer,
  historyDeal,
};
