const authentication = {
  LOGIN_ADMIN: 'LOGIN_ADMIN',
  LOGOUT_ADMIN: 'LOGOUT_ADMIN',
  LOGIN_REQUEST: 'MEMBER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'MEMBER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'MEMBER_LOGIN_FAILURE',

  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',
};
const employeeManage = {
  LOAD_LIST_EMPLOYEE: 'LOAD_LIST_EMPLOYEE',
  TOGGLE_DETAILS: 'TOGGLE_DETAILS',
};

const statistic = {
  GET_TRANSACTION_HISTORY: 'GET_TRANSACTION_HISTORY',
};
export const administratorConstants = {
  authentication,
  employeeManage,
  statistic,
};
