const authentication = {
  LOGIN_REQUEST: 'MEMBER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'MEMBER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'MEMBER_LOGIN_FAILURE',

  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  LOGOUT: 'MEMBER_LOGOUT',
};
const employeeManage = {
  LOAD_LIST_EMPLOYEE: 'LOAD_LIST_EMPLOYEE',
  TOGGLE_DETAILS: 'TOGGLE_DETAILS',
};
export const administratorConstants = {
  authentication,
  employeeManage,
};
